import type { Transaction, Workspace } from '@folyo/domain';

const accountIds = {
  bank: 'sample-bank',
  card: 'sample-card',
  cash: 'sample-cash',
};

const transaction = (
  id: string,
  accountId: string,
  occurredAt: string,
  amount: number,
  direction: Transaction['direction'],
  rawDescription: string,
  kind: Transaction['kind'],
  category: string,
): Transaction => ({
  id,
  accountId,
  occurredAt,
  amount,
  currency: 'INR',
  direction,
  rawDescription,
  displayMerchant: rawDescription,
  category,
  kind,
  source: 'sample',
  sourceReference: `sample-${id}`,
});

export const sampleWorkspace: Workspace = {
  accounts: [
    {
      id: accountIds.bank,
      name: 'Everyday bank',
      kind: 'bank',
      currency: 'INR',
      openingBalance: 2200000,
    },
    { id: accountIds.card, name: 'Travel card', kind: 'card', currency: 'INR', openingBalance: 0 },
    {
      id: accountIds.cash,
      name: 'Cash pocket',
      kind: 'cash',
      currency: 'INR',
      openingBalance: 150000,
    },
  ],
  transactions: [
    transaction(
      's-001',
      accountIds.bank,
      '2025-04-01',
      12500000,
      'in',
      'Wyrcan salary',
      'income',
      'Income',
    ),
    transaction(
      's-002',
      accountIds.bank,
      '2025-04-02',
      189900,
      'out',
      'Rent transfer',
      'spending',
      'Home',
    ),
    transaction(
      's-003',
      accountIds.bank,
      '2025-04-03',
      89900,
      'out',
      'Streamly',
      'spending',
      'Subscriptions',
    ),
    transaction(
      's-004',
      accountIds.bank,
      '2025-04-04',
      43000,
      'out',
      'Green Bowl',
      'spending',
      'Food',
    ),
    transaction(
      's-005',
      accountIds.bank,
      '2025-04-07',
      1000000,
      'out',
      'Transfer to Travel card',
      'transfer',
      'Transfer',
    ),
    transaction(
      's-006',
      accountIds.card,
      '2025-04-07',
      1000000,
      'in',
      'Transfer from Everyday bank',
      'transfer',
      'Transfer',
    ),
    transaction(
      's-007',
      accountIds.card,
      '2025-04-12',
      220000,
      'out',
      'Railway tickets',
      'spending',
      'Travel',
    ),
    transaction(
      's-008',
      accountIds.bank,
      '2025-04-18',
      25000,
      'out',
      'Green Bowl',
      'spending',
      'Food',
    ),
    transaction(
      's-009',
      accountIds.bank,
      '2025-04-21',
      89900,
      'out',
      'Streamly',
      'spending',
      'Subscriptions',
    ),
    transaction(
      's-010',
      accountIds.bank,
      '2025-05-01',
      12500000,
      'in',
      'Wyrcan salary',
      'income',
      'Income',
    ),
    transaction(
      's-011',
      accountIds.bank,
      '2025-05-02',
      189900,
      'out',
      'Rent transfer',
      'spending',
      'Home',
    ),
    transaction(
      's-012',
      accountIds.bank,
      '2025-05-04',
      89900,
      'out',
      'Streamly',
      'spending',
      'Subscriptions',
    ),
    transaction(
      's-013',
      accountIds.bank,
      '2025-05-06',
      66000,
      'out',
      'Green Bowl',
      'spending',
      'Food',
    ),
    transaction(
      's-014',
      accountIds.card,
      '2025-05-10',
      310000,
      'out',
      'Mountain stay',
      'spending',
      'Travel',
    ),
    transaction(
      's-015',
      accountIds.bank,
      '2025-05-17',
      45000,
      'out',
      'Metro recharge',
      'spending',
      'Travel',
    ),
    transaction(
      's-016',
      accountIds.bank,
      '2025-05-22',
      125000,
      'in',
      'Mountain stay refund',
      'refund',
      'Travel',
    ),
    transaction(
      's-017',
      accountIds.bank,
      '2025-05-24',
      45000,
      'out',
      'Green Bowl',
      'spending',
      'Food',
    ),
    transaction(
      's-018',
      accountIds.bank,
      '2025-05-27',
      89900,
      'out',
      'Streamly',
      'spending',
      'Subscriptions',
    ),
    transaction(
      's-019',
      accountIds.bank,
      '2025-06-01',
      12500000,
      'in',
      'Wyrcan salary',
      'income',
      'Income',
    ),
    transaction(
      's-020',
      accountIds.bank,
      '2025-06-02',
      189900,
      'out',
      'Rent transfer',
      'spending',
      'Home',
    ),
    transaction(
      's-021',
      accountIds.bank,
      '2025-06-04',
      119900,
      'out',
      'Streamly Plus',
      'spending',
      'Subscriptions',
    ),
    transaction(
      's-022',
      accountIds.bank,
      '2025-06-05',
      94000,
      'out',
      'Green Bowl',
      'spending',
      'Food',
    ),
    transaction(
      's-023',
      accountIds.card,
      '2025-06-09',
      740000,
      'out',
      'Flight to Kochi',
      'spending',
      'Travel',
    ),
    transaction(
      's-024',
      accountIds.bank,
      '2025-06-12',
      28000,
      'out',
      'Green Bowl',
      'spending',
      'Food',
    ),
    transaction(
      's-025',
      accountIds.bank,
      '2025-06-15',
      220000,
      'out',
      'Laptop sleeve',
      'spending',
      'Shopping',
    ),
    transaction(
      's-026',
      accountIds.bank,
      '2025-06-20',
      80000,
      'out',
      'Green Bowl',
      'spending',
      'Food',
    ),
    transaction(
      's-027',
      accountIds.bank,
      '2025-06-28',
      119900,
      'out',
      'Streamly Plus',
      'spending',
      'Subscriptions',
    ),
  ],
};
